[package]
name = "alegacy-quest-editor"
version = "0.2.0"
description = "Alegacy Quest Editor"
authors = ["you"]
edition = "2021"

[lib]
name = "alegacy_quest_editor_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
walkdir = "2"
